config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  get 'signup'=> 'users#new'
  resources :users, except: [:new] 


   resources :customers
   resources :categories
   resources  :products
   resources  :bejaks 
   resources  :bejak_details
   resources  :invoices
   resources  :invoice_details
   resources  :wastes
   resources  :current_prices
   resources  :expenditures

   get 'sign_in', to: "sessions#new"
 post 'sign_in', to: "sessions#create"
 delete 'logout' => 'sessions#destroy'
 get 'search_customers', to: 'customers#search'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bejak.rb
class Bejak < ApplicationRecord
    has_many :bejak_details,  dependent: :destroy
    has_many  :wastes,          dependent: :destroy


    
  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( date AS  text) LIKE ? ", "%#{search}%"])   
     else   
       all.order(created_at: :desc)
     end 
  end
end

app/models/bejak_detail.rb
class BejakDetail < ApplicationRecord
  belongs_to :product
  belongs_to :bejak

  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( created_at AS  text) LIKE ? ", "%#{search}%"])   
     else   
       all.order(created_at: :desc)
     end 
  end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products,  dependent: :destroy

    paginates_per 2

    self.inheritance_column="not_sti"
    def self.search(search)
       if search
          where(["category_name LIKE ? ", "%#{search}%"])
       else   
         all.order(created_at: :desc)
       end 
 
    end
end

app/models/current_price.rb
class CurrentPrice < ApplicationRecord
  belongs_to :product

  
  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( created_at AS  text) LIKE ? ", "%#{search}%"])
      
     else   
       all.order(created_at: :desc)
     end 
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
   has_many  :invoices,  dependent: :destroy
   paginates_per 5


   self.inheritance_column="not_sti"
   
   def self.search( search)
      if search
         where(["full_name || address || phone LIKE ? ", "%#{search}%"])
      else   
        all.order(created_at: :desc)
      end 

   end

# def self.search(param)
#    to_send_back= (full_name_matches(param) + address_matches(param) + phone_matches(param)).uniq
#    return nil unless to_send_back
#    to_send_back

# end

# def self.full_name_matches(param)
#    matches('full_name', param)
# end

# def self.address_matches(param)
#    matches('address', param)
# end

# def self.phone_matches(param)
#    matches('phone', param)
# end
 
#  def self.matches(field_name, param)
#    if field_name && param
#            Customer.where("#{field_name} LIKE ? ", "%#{param}%")
#         else   
#           all.order(created_at: :desc)
#          end 
#  end

end

app/models/expenditure.rb
class Expenditure < ApplicationRecord

    
  paginates_per 4

  self.inheritance_column="not_sti"
  def self.search(search)
     if search
        where([" CAST( date AS  text) LIKE ? ", "%#{search}%"])   
      
     else   
       all.order(created_at: :desc)
     end 

  end
end

app/models/finance.rb
class Finance < ApplicationRecord
  belongs_to :customer
  belongs_to :invoice
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many  :invoice_details,  dependent: :destroy

    
  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( date AS  text) LIKE ? ", "%#{search}%"])   
     else   
       all.order(created_at: :desc)
     end 
  end
end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
  belongs_to :product
  belongs_to :invoice

  
  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( created_at AS  text) LIKE ? ", "%#{search}%"])   
     else   
       all.order(created_at: :desc)
     end 
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :bejak_details,  dependent: :destroy
  has_many  :invoice_details,  dependent: :destroy
  has_many  :wastes,           dependent: :destroy
  has_many  :current_prices,  dependent: :destroy
  
  paginates_per 4

  self.inheritance_column="not_sti"
  def self.search(search)
     if search
        where(["product_details LIKE ? ", "%#{search}%"])
      
     else   
       all.order(created_at: :desc)
     end 

  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
 validates :fullname,  presence: true, uniqueness: true
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, presence: true , uniqueness: true, length:{maximum:105},
                 format:{with:VALID_EMAIL_REGEX} 
                         
end

app/models/waste.rb
class Waste < ApplicationRecord
  belongs_to :product
  belongs_to :bejak
  

  
  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( created_at AS  text) LIKE ? ", "%#{search}%"])   
     else   
       all.order(created_at: :desc)
     end 
  end
  
end

app/controllers/wastes_controller.rb
class WastesController < ApplicationController

  before_action :require_user_logged_in 
  before_action  :set_waste, only: [:edit, :update, :destroy]

  def index
    @waste= Waste.search(params[:search]).page(params[:page]) 
  end


  def edit 
  
  end

  def update 
    if @waste.update(waste_params)
      redirect_to wastes_path
      else
        render "edit"
      end
  end

  def new 
    @waste=Waste.new
 end


 def create 
    @bejak=Bejak.last
   @waste=Waste.new(waste_params)
    @waste.bejak= @bejak
   if  @waste.save
     
     redirect_to wastes_path
   else 
     render "new"
   end
 end 

  private 

   def waste_params
    params.require(:waste).permit(:details, :unit, :quantity, :unit_price, :product_id)
   end

   def set_waste
    @waste=Waste.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bejaks_helper.rb
module BejaksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wastes_helper.rb
module WastesHelper
end

app/views/wastes/_form.html.erb
<%= form_with model: @waste, url:  wastes_path    do |waste| %>


    <div class="flex flex-col m-auto  gap-3 w-[70%] ">
      <div class="flex flex-col ">
        <lable for='name'>‌ Product Name </lable>
        <%=waste.select :product_id, Product.pluck(:product_details, :id)  ,
        class:"peer border border-slate-400  rounded-md bg-white " %>      
     </div>

    <div class="flex flex-col" >
        <lable for='name'>Wast Details</lable>
        <%=  waste.text_area :details, autofocus: true,  cols: 30, rows: 2, :required=> true,  placeholder:"Bejak Details",
        class:"peer border border-slate-400  rounded-md bg-white " %>  
   </div>

    <div class="flex flex-col ">
        <lable for='name'>Unit</lable>
        <%=   waste.text_field :unit, autofocus: true, :required=> true,   placeholder:"Unit",
        class:"peer border border-slate-400  rounded-md bg-white " %>             
    </div>

   

    <div class="flex flex-col ">
        <lable for='name'>Quantity</lable>
        <%= waste.number_field :quantity, autofocus: true, :required=> true,   placeholder:"Quantity",
        class:"peer border border-slate-400  rounded-md bg-white " %>          
    </div>
    <div class="flex flex-col ">
        <lable for='name'>Unit Price</lable>
        <%=  waste.number_field :unit_price, autofocus: true, step: :any, :required=> true,  placeholder:"Unit Price",
        class:"peer border border-slate-400  rounded-md bg-white " %>          
    </div>
    
   <div class="flex  justify-between ">
     <div class="flex">
      <%= waste.submit  "Save", class:" w-20 p-2  text-white font-bold cursor-pointer bg-blue-500 rounded-md" %>
     </div>

     <div class='flex'>
     <%= link_to "Back",wastes_path, class:" w-20 p-2  text-white text-center font-bold cursor-pointer bg-slate-600 rounded-md" %>
     </div>

    </div>
   </div>
<% end %>

app/views/wastes/edit.html.erb
<div class=" flex flex-col  w-[80%]   gap-8  m-auto rounded-md bg-zinc-300 pb-10 pt-6">

<h1 class="text-2xl  mr-10 flex flex-col items-center   font-bold">Update Waste </h1>

<%= render 'form' %>

</div>

app/views/wastes/index.html.erb
<div class=" flex flex-col  w-[100%]  gap-4  m-auto rounded-md  pt-6 relative overflow-x-auto bg-zinc-300  ">

<div class="flex justify-between">
     <div class="flex px-4 ">
      <h1 class=" flex  text-2xl font-bold">Wastes List</h1>
      </div>
      <div class="flex ml-20 ">
          <%= form_with( url: bejak_details_path,  method:  :get , local: true)  do %>
          <%= text_field_tag (:search), "", class:' w-1/2  ml-20 rounded-md' %>
          <%= submit_tag("Search", :class=>"cursor-pointer font-bold cursor-pointer p-2 bg-lime-700 rounded-md ")  %>
          <% end %>
      </div>
</div>

<div class="flex flex-col items-end  mr-14">
<%= link_to 'Add New ',new_waste_path, class:" w-15 p-2 text-white font-bold cursor-pointer bg-cyan-600 rounded-md" %>
</div>
  <table class=" w-[100%]  m-auto text-sm text-gray-500 dark:text-gray-400 text-center ">
    <thead class="text-lg text-gray-700   dark:bg-gray-700 dark:text-gray-400  border-b" >
      <tr>
      <th> Wastes Details</th>
      <th> Unit </th>
      <th> Quatity </th>
      <th> Unit Price </th>
      <th> Total Price </th>
      <th> Edit </th>
      <th> Delete </th> 
      </tr>
    </thead >
    <tbody>
  
    <%@waste.each do |bejak|%>
 
        <tr class="border-b">
            <td> <%= bejak.details %> </td>
            <td> <%= bejak.unit %> </td>
            <td> <%= bejak.quantity %> </td>
            <td> <%= bejak.unit_price %> </td>
            <td> <%= bejak.quantity * bejak.unit_price %> </td>
            <td>
            <%= link_to 'Edit', edit_waste_path(bejak), class:" p-2 text-white font-bold cursor-pointer bg-lime-600 rounded-md"  %></td>
            <td>
         
           <%= button_to 'Remove',  waste_path(bejak), method: :delete, method: :delete, class:"  p-2 text-white font-bold cursor-pointer bg-red-500 rounded-md" %>
       
          </td>
        </tr>
       
      <%end%> 
      
    </tbody>                  
  </table>
  <%= paginate @waste %>
  
  </div>

app/views/wastes/new.html.erb
<h1> Add New Waste </h1>
<%= render 'form' %>