config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  get 'signup'=> 'users#new'
  resources :users, except: [:new] 


   resources :customers
   resources :categories
   resources  :products
   resources  :bejaks 
   resources  :bejak_details
   resources  :invoices
   resources  :invoice_details
   resources  :wastes
   resources  :current_prices
   resources  :expenditures

   get 'sign_in', to: "sessions#new"
 post 'sign_in', to: "sessions#create"
 delete 'logout' => 'sessions#destroy'
 get 'search_customers', to: 'customers#search'
 
end

app/models/bejak.rb
class Bejak < ApplicationRecord
    has_many :bejak_details,  dependent: :destroy
    has_many  :wastes,          dependent: :destroy


    
  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( date AS  text) LIKE ? ", "%#{search}%"])   
     else   
       all.order(created_at: :desc)
     end 
  end
end

app/models/bejak_detail.rb
class BejakDetail < ApplicationRecord
  belongs_to :product
  belongs_to :bejak

  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( created_at AS  text) LIKE ? ", "%#{search}%"])   
     else   
       all.order(created_at: :desc)
     end 
  end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products,  dependent: :destroy

    paginates_per 2

    self.inheritance_column="not_sti"
    def self.search(search)
       if search
          where(["category_name LIKE ? ", "%#{search}%"])
       else   
         all.order(created_at: :desc)
       end 
 
    end
end

app/models/current_price.rb
class CurrentPrice < ApplicationRecord
  belongs_to :product

  
  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( created_at AS  text) LIKE ? ", "%#{search}%"])
      
     else   
       all.order(created_at: :desc)
     end 
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
   has_many  :invoices,  dependent: :destroy
   paginates_per 5


   self.inheritance_column="not_sti"
   
   def self.search( search)
      if search
         where(["full_name || address || phone LIKE ? ", "%#{search}%"])
      else   
        all.order(created_at: :desc)
      end 

   end

# def self.search(param)
#    to_send_back= (full_name_matches(param) + address_matches(param) + phone_matches(param)).uniq
#    return nil unless to_send_back
#    to_send_back

# end

# def self.full_name_matches(param)
#    matches('full_name', param)
# end

# def self.address_matches(param)
#    matches('address', param)
# end

# def self.phone_matches(param)
#    matches('phone', param)
# end
 
#  def self.matches(field_name, param)
#    if field_name && param
#            Customer.where("#{field_name} LIKE ? ", "%#{param}%")
#         else   
#           all.order(created_at: :desc)
#          end 
#  end

end

app/models/expenditure.rb
class Expenditure < ApplicationRecord

    
  paginates_per 4

  self.inheritance_column="not_sti"
  def self.search(search)
     if search
        where([" CAST( date AS  text) LIKE ? ", "%#{search}%"])   
      
     else   
       all.order(created_at: :desc)
     end 

  end
end

app/models/finance.rb
class Finance < ApplicationRecord
  belongs_to :customer
  belongs_to :invoice
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many  :invoice_details,  dependent: :destroy

    
  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( date AS  text) LIKE ? ", "%#{search}%"])   
     else   
       all.order(created_at: :desc)
     end 
  end
end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
  belongs_to :product
  belongs_to :invoice

  
  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( created_at AS  text) LIKE ? ", "%#{search}%"])   
     else   
       all.order(created_at: :desc)
     end 
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :bejak_details,  dependent: :destroy
  has_many  :invoice_details,  dependent: :destroy
  has_many  :wastes,           dependent: :destroy
  has_many  :current_prices,  dependent: :destroy
  
  paginates_per 4

  self.inheritance_column="not_sti"
  def self.search(search)
     if search
        where(["product_details LIKE ? ", "%#{search}%"])
      
     else   
       all.order(created_at: :desc)
     end 

  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
 validates :fullname,  presence: true, uniqueness: true
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, presence: true , uniqueness: true, length:{maximum:105},
                 format:{with:VALID_EMAIL_REGEX} 
                         
end

app/models/waste.rb
class Waste < ApplicationRecord
  belongs_to :product
  belongs_to :bejak
  

  
  paginates_per 4

  self.inheritance_column="not_sti"

  def self.search(search)
     if search
        where([" CAST( created_at AS  text) LIKE ? ", "%#{search}%"])   
     else   
       all.order(created_at: :desc)
     end 
  end
  
end

app/helpers/bejaks_helper.rb
module BejaksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wastes_helper.rb
module WastesHelper
end

app/views/shared/_footer.html.erb
<footer class="bg-gray-200 text-center lg:text-left mb-0">
  <div class="text-gray-700 text-center p-4" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-gray-800" href="https://tailwind-elements.com/">Tailwind Elements</a>
  </div>
</footer>

app/views/shared/_messages.html.erb
<p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

app/views/shared/_navbar.html.erb
<div class=" bg-white flex flex-col  w-full  ">

<style>
    @media only screen and (min-width: 768px){
        .parent:hover .child {
            opacity:1;
            height:auto;
            overflow:none;
            transform: translateY(0);
        }
        .child {
            opacity:1;
            height:0;
            overflow:hidden;
            transform: translateY(-30%);
        }
    }
    
</style>

    <nav class="flex justify-between px-6 border-b md:shadow-lg items-center  h-16 ">
        <div class="text-lg font-bold md:py-0 py-4">
            Logo
        </div>
       
        <ul class="flex">
        <% if @current_user %>
           
            <li class="relative parent">
                    <%= link_to "مشتریان", customers_path , class:" flex justify-between md:inline-flex p-4 items-center hover:bg-gray-200 space-x-2" %>   
            </li>

            <li class="relative parent flex items-center hover:bg-gray-200 px-1">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 fill-current pt-1  mt-1 " viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
           
                 <%= link_to "کتگوری",categories_path, class:"flex justify-between md:inline-flex px-0.5 items-center "  %>
 
                <ul class="child transition duration-300 md:absolute top-full right-0 md:w-28 bg-white md:shadow-lg md:rounded-b ">
                    <li> 
                        <%= link_to "پرودکت",products_path , class:"flex px-4 py-3 hover:bg-gray-50"  %>
                    </li>  
                </ul>
            </li>
            <li class="relative parent flex items-center hover:bg-gray-200 px-4">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 fill-current pt-1  mt-1 " viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
           
                 <%= link_to  "خریداری",bejaks_path, class:"flex justify-between md:inline-flex px-0.5 items-center "  %>
         
             
                <ul class="child transition duration-300 md:absolute top-full right-0  md:w-40 bg-white md:shadow-lg md:rounded-b ">
                    <li>
                        
                        <%= link_to "جزئیات خریداری",bejak_details_path , class:"flex flex-col items-center px-1 py-3 hover:bg-gray-100"  %>
                    </li>  
                </ul>
                <ul class="child transition duration-300 md:absolute top-full right-0  md:w-40 bg-white md:shadow-lg md:rounded-b ">
                    <li>
                        
                        <%= link_to "جزئیات خریداری",bejak_details_path , class:"flex flex-col items-center px-1 py-3 hover:bg-gray-100"  %>
                    </li>  
                    <li>
                        
                        <%= link_to "نرخ اجناس",current_prices_path , class:"flex flex-col items-center px-1 py-3 hover:bg-gray-100"  %>
                    </li>  
                </ul>
                
                
            </li>
           
            <li class="relative parent flex items-center hover:bg-gray-200 px-1">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 fill-current pt-1  mt-1 " viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
           
                 <%= link_to  "فروشات",invoices_path, class:"flex justify-between md:inline-flex px-0.5 items-center   "  %>
         
             
                <ul class="child transition duration-300 md:absolute top-full right-0  md:w-40 bg-white md:shadow-lg md:rounded-b ">
                    <li>
                        
                        <%= link_to "جزئیات فروشات",invoice_details_path , class:"flex flex-col items-center px-1 py-3 hover:bg-gray-100"  %>
                    </li>  
                </ul>
            </li>
            <li class="relative parent flex items-center hover:bg-gray-200 px-1">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 fill-current pt-1  mt-1 " viewBox="0 0 24 24"><path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"/></svg>
           
                 <%= link_to  "مالی", class:"flex justify-between md:inline-flex px-0.5 items-center  "  %>
         
             
                
                <ul class="child transition duration-300 md:absolute top-full right-0  md:w-40 bg-white md:shadow-lg md:rounded-b ">
                    <li>
                        
                        <%= link_to "مصارفات",expenditures_path, class:"flex flex-col items-center px-1 py-3 hover:bg-gray-100"  %>
                    </li>  
                    <li>
                        
                        <%= link_to "ضایعات",wastes_path, class:"flex flex-col items-center px-1 py-3 hover:bg-gray-100"  %>
                    </li>  
                </ul>
            </li>
            <% end %>
        </ul>
       <div>
      
       <ul class='flex gap-4'>
       <% if @current_user %>
       <li class="mt-1.5">
       Welcom! <%= @current_user.fullname %> 
      </li> 
      <li>
      <%=  button_to "Sign out" , logout_path, method: :delete, class:"w-full px-2 py-1 text-white font-bold cursor-pointer bg-blue-500 rounded-md"  %>
      </li>
      <% else %>
      <li> 
        <%= link_to "Sign in", sign_in_path,class:"w-full p-2 text-white font-bold cursor-pointer bg-blue-500 rounded-md" %>
      </li>
      <li>
      <%= link_to "Sign up",signup_path , class:"w-full p-2 text-white font-bold cursor-pointer bg-blue-500 rounded-md"%>
    </li>
    
      <%end%>
       </ul>
       </div>
        
    </nav>
</div>